refactor: change product schema to m2m
Crabti/gaqsa pull request #61
Opened 2021-11-09 15:57 UTC by albertcastaned

## ¿Qué hace este PR?
- Cambia el modelo de producto a m2n con relación a proveedor. Los campos: Precio, Iva, y Laboratorio se movieron a la tabla intermedia entre proveedor y producto. Esto basándome en lo que nos han enseñado y tienen en migración.
- Ajustes a vistas tanto en frontend como en backend para este nuevo schema.
- Agrega unas nuevas vistas también basadas en migración para tener mas opciones en la lista de peticiones de producto. Una petición de producto (un producto registrado por un proveedor con un estado pendiente) puede: Registrarse como un producto (cambia el estado), ser rechazado (también cambia el estado, y ser agrupado con un producto existente. Agrupar con un producto existente cambia el estado de la petición de producto y ademas agrega los datos de la petición (precio, iva, laboratorio y al mismo proveedor) a la relación del producto existente seleccionado. De esta forma tendrán mas control sobre agrupación de productos.
- Las acciones anteriores se pueden hacer de forma masiva, se pueden remplazar los datos de iva, laboratorio, y precio por el admin antes de hacer una acción.
- La vista de detalle y modificar de producto no pone los campos específicos de la relación de un producto por lo pronto solo los del producto base (nombre, presentación, categoría, etc.). 

## ¿Cuáles son los tickets relevantes de JIRA?
- GAQ-196
## Screenshots (Si aplica)
![image](https://user-images.githubusercontent.com/38927620/140957767-6fb850fe-fe05-4099-9ce1-c833a3402412.png)

![image](https://user-images.githubusercontent.com/38927620/140958652-66776e77-869b-4ed5-bdc8-4f497df63ef4.png)
![image](https://user-images.githubusercontent.com/38927620/140958762-4eb1781f-e1d3-41fe-9e1d-db26b933529f.png)

![image](https://user-images.githubusercontent.com/38927620/140958431-4213b40e-3a72-455d-b335-87c3f976395b.png)

2021-11-09 20:35 UTC, scarlosro approved these changes
LGTM
Probe en ambiente local y todo me funciono bien.

2021-11-09 20:48 UTC, albertcastaned commented
> LGTM Probe en ambiente local y todo me funciono bien.

¿Tuviste que modificar tu base de datos o algo así?

2021-11-09 20:52 UTC, scarlosro commented
> > LGTM Probe en ambiente local y todo me funciono bien.
> 
> ¿Tuviste que modificar tu base de datos o algo así?



> > LGTM Probe en ambiente local y todo me funciono bien.
> 
> ¿Tuviste que modificar tu base de datos o algo así?

Tuve que eliminar la de productos por aprobar ya que me hacía error de colapso, en cuestión a las demás vistas trabajo bien en los tres roles.

2021-11-09 21:43 UTC, albertcastaned commented
> > > LGTM Probe en ambiente local y todo me funciono bien.
> > 
> > 
> > ¿Tuviste que modificar tu base de datos o algo así?
> 
> > > LGTM Probe en ambiente local y todo me funciono bien.
> > 
> > 
> > ¿Tuviste que modificar tu base de datos o algo así?
> 
> Tuve que eliminar la de productos por aprobar ya que me hacía error de colapso, en cuestión a las demás vistas trabajo bien en los tres roles.

OK gracias. Creo que esperare a una revisión mas para pasarlo a staging y hacer los ajustes para que funcione en producción. Mientras si necesitas esta rama para lo de pedidos la puedes usar no creo que esa parte cambie mucho si hace falta cambios.

2021-11-10 00:07 UTC, Topi99 commented
No se cómo se maneje el registro de productos por parte de proveedores en el sistema actual de Gaqsa, pero creo podemos mejorar la UX del nuestro con este nuevo cambio. 
![image](https://user-images.githubusercontent.com/11434828/141025351-7c2664ee-d76f-4278-84cd-ee8a4497999c.png)

Se supone que los productos ya existen, solamente los proveedores dicen que lo tienen en su catálogo y les asignan un precio, ¿verdad? De ser así, podemos mostrar una lista o una barra de búsqueda para los proveedores en la vista que puse. ¿Cómo ves?

2021-11-10 00:34 UTC, Topi99 requested changes
Creo debemos cambiar el mensaje de éxito cuando se aceptan productos: 

![image](https://user-images.githubusercontent.com/11434828/141027526-f06184a1-ecc5-49f3-b398-6ba080b786d8.png)

Para que sea algo como: "Producto(s) aceptado(s) exitosamente".

2021-11-10 00:34 UTC, Topi99 approved these changes
Perdón, era un comentario que no bloquea jaja.

2021-11-10 00:41 UTC, albertcastaned commented
> No se cómo se maneje el registro de productos por parte de proveedores en el sistema actual de Gaqsa, pero creo podemos mejorar la UX del nuestro con este nuevo cambio. ![image](https://user-images.githubusercontent.com/11434828/141025351-7c2664ee-d76f-4278-84cd-ee8a4497999c.png)
> 
> Se supone que los productos ya existen, solamente los proveedores dicen que lo tienen en su catálogo y les asignan un precio, ¿verdad? De ser así, podemos mostrar una lista o una barra de búsqueda para los proveedores en la vista que puse. ¿Cómo ves?



> No se cómo se maneje el registro de productos por parte de proveedores en el sistema actual de Gaqsa, pero creo podemos mejorar la UX del nuestro con este nuevo cambio. ![image](https://user-images.githubusercontent.com/11434828/141025351-7c2664ee-d76f-4278-84cd-ee8a4497999c.png)
> 
> Se supone que los productos ya existen, solamente los proveedores dicen que lo tienen en su catálogo y les asignan un precio, ¿verdad? De ser así, podemos mostrar una lista o una barra de búsqueda para los proveedores en la vista que puse. ¿Cómo ves?

Si es muy buena idea. De hecho nos habían pedido hace dos juntas que viéramos si era posible aunque creo que para la vista como admins. No se si los proveedores tienen permitido ver la información de los productos existentes del sistema, en la vista de lista de productos se filtran ahorita. ¿Te parece si lo registro como un issue para que lo validemos con ellos y se resuelva despues?

2021-11-10 02:24 UTC, merged